from typing import Dict, Any
from src.state import GraphState
from src.mcp_registry import registry

def script_validator_node(state: GraphState) -> GraphState:
    """
    Mode 1: Validates a manually uploaded script.
    Checks for basic structure, then uses MCP to parse it into JSON.
    """
    print("\n[AGENT: SCRIPT VALIDATOR] Inspecting manual script...")
    raw_text = state.get("raw_prompt", "")
    
    errors = []
    # Basic validation: A real script usually has scene headings like INT. or EXT.
    if "INT." not in raw_text and "EXT." not in raw_text:
        errors.append("Missing scene headings (e.g., INT. or EXT.).")
        
    if errors:
        state["status"] = "failed"
        state["errors"] = errors
        print(f"[ERROR] Validation failed: {errors}")
    else:
        # If passed, dynamically use MCP to convert it to standardized JSON
        print("-> Calling MCP Tool 'parse_manual_script'")
        mcp_result = registry.execute_tool("parse_manual_script", raw_text=raw_text)
        
        if mcp_result["status"] == "success":
            state["script"] = mcp_result["script"]
            state["status"] = "processing"
            print("[SUCCESS] Script is valid and successfully parsed into JSON.")
        else:
            state["errors"] = ["Failed to parse script format into JSON."]
            state["status"] = "failed"
        
    return state


def scriptwriter_node(state: GraphState) -> GraphState:
    """
    Mode 2: Autonomously generates a script from a prompt.
    Must use the MCP tool dynamically to satisfy constraints.
    """
    print("\n[AGENT: SCRIPTWRITER] Generating script from prompt...")
    prompt = state.get("raw_prompt", "Default story prompt")
    
    # CONSTRAINT: Must not use hardcoded APIs. Dynamically execute via MCP.
    print(f"-> Calling MCP Tool 'generate_script_segment' for: '{prompt}'")
    mcp_result = registry.execute_tool("generate_script_segment", prompt=prompt, num_scenes=1)
    
    # IMPORTANT FIX: Use the actual script generated by the tool, NOT the hardcoded mock!
    if mcp_result["status"] == "success":
        state["script"] = mcp_result["script"]
        state["status"] = "processing"
        print("[SUCCESS] Script autonomously generated and structured.")
    else:
        state["script"] = mcp_result["script"] # Uses the fallback error script
        state["status"] = "failed"
        state["errors"] = [mcp_result["message"]]
        print("[ERROR] Failed to generate script.")
    
    return state
# =====================================================================
# TESTING THE NODES
# =====================================================================
if __name__ == "__main__":
    # Test Mode 1: Validation (Failing Scenario)
    test_state_1: GraphState = {
        "input_mode": "manual",
        "raw_prompt": "Just a random story without scene headings.",
        "script": {}, "characters": [], "images": [], "status": "processing", "errors": []
    }
    script_validator_node(test_state_1)

    # Test Mode 2: Auto Generation
    test_state_2: GraphState = {
        "input_mode": "auto",
        "raw_prompt": "A sci-fi standoff in a neon city.",
        "script": {}, "characters": [], "images": [], "status": "processing", "errors": []
    }
    final_state = scriptwriter_node(test_state_2)
    
    print("\n--- FINAL STATE CHECK ---")
    print(f"Generated Script Location: {final_state['script']['scenes'][0]['location']}")